pluginManagement {
    repositories {
        google()
        mavenCentral()
        maven { url "https://chaquo.com/maven" }
        gradlePluginPortal()
    }
}

include ':sample'
project(':sample').projectDir = new File(rootProject.projectDir, '../android-sdk-v5-sample')

include ':uxsdk'// uxsdk模块
project(':uxsdk').projectDir = new File(rootProject.projectDir, '../android-sdk-v5-uxsdk')
